# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure
import numpy as np


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def refresh_number():
    canvas.itemconfig(front, text="1")


window = Tk()

window.geometry("1000x800")
window.configure(bg="#FFFFFF")
window.title("Self driving car")

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 800,
    width = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    250.0,
    0.0,
    1000.0,
    100.0,
    fill="#8D99AE",
    outline="")

canvas.create_rectangle(
    250.0,
    100.0,
    1000.0,
    800.0,
    fill="#EDF2F4",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    250.0,
    800.0,
    fill="#2B2D42",
    outline="")

canvas.create_text(
    250.0,
    33.0,
    anchor="nw",
    text="Left",
    fill="#FFFFFF",
    font=("Segoe UI", 24 * -1)
)

canvas.create_text(
    500.0,
    33.0,
    anchor="nw",
    text="Front",
    fill="#FFFFFF",
    font=("Segoe UI", 24 * -1)
)

canvas.create_text(
    750.0,
    33.0,
    anchor="nw",
    text="Right",
    fill="#FFFFFF",
    font=("Segoe UI", 24 * -1)
)

right = canvas.create_text(
    900.0,
    33.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Segoe UI", 24 * -1)
)

front = canvas.create_text(
    650.0,
    33.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Segoe UI", 24 * -1)
)

left = canvas.create_text(
    400.0,
    33.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Segoe UI", 24 * -1)
)

canvas.create_text(
    67.0,
    130.0,
    anchor="nw",
    text="Load Map",
    fill="#FFFFFF",
    font=("Segoe UI", 24 * -1)
)

canvas.create_text(
    50.0,
    284.0,
    anchor="nw",
    text="Load Records",
    fill="#FFFFFF",
    font=("Segoe UI", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=refresh_number,
    relief="flat",
)
button_1.place(
    x=50.0,
    y=594.0,
    width=150.0,
    height=60.0
)
# ------------------------- try new things
fig = Figure(figsize=(5, 4), dpi=100)
plot1 = fig.add_subplot(111)

plot1.plot([3, 5], [1, 6], color="green")
plt.xlabel("X")
plt.ylabel("Y")

canvas1 = FigureCanvasTkAgg(fig, master=window)  # A tk.DrawingArea.
canvas1.draw()
canvas1.get_tk_widget().place(x=250, y=100, width=750, height=700)


# ---------------------------------

window.resizable(False, False)
window.mainloop()
